[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGS NF"

[font.italic]
family = "MesloLGS NF"

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002,"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002N"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002$"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002q"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002X"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000F"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002w"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-i", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Windowed"
option_as_alt = "Both"
blur = true
opacity = 0.9


[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Command|Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[general]
live_config_reload = true
